Repository marcosdosea/Cuidado, pull requests merged in 2024-09, with the labels that each got.

#43 Guia de estilo adicionado
  Requisitos/Telas/CuidadoStyleGuide.pdf
Labels: enhancement

#38 Atualização dos casos de uso.
  Requisitos/CSU11 - Manter Responsável.docx
  Requisitos/CSU12 - Manter Planejamento Cuidado.docx
  Requisitos/CSU13 - Manter Fornecedor.docx
  Requisitos/CSU14 - Manter Organizacao.docx
  Requisitos/CSU15 - Realizar Cuidado.docx
Labels: documentation, enhancement

#89 Implentação do controller do cuidado
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/CuidadoController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/FuncionarioController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/ProdutoController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/VisitanteController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Mappers/CuidadoProfile.cs
  Codigo/CuidadoWeb/CuidadoWeb/Models/CuidadoViewModel.cs
Labels: enhancement

#88 Implementação do CuidadoService - #71
  Codigo/CuidadoWeb/Core/Service/IAcompanhanteService.cs
  Codigo/CuidadoWeb/Core/Service/IAquisicaoProdutoService.cs
  Codigo/CuidadoWeb/Core/Service/IAquisicaoService.cs
  Codigo/CuidadoWeb/Core/Service/IAtividadeExternaService.cs
  Codigo/CuidadoWeb/Core/Service/IConsultaService.cs
  Codigo/CuidadoWeb/Core/Service/ICuidadoService.cs
  Codigo/CuidadoWeb/Core/Service/IEspecialidadeMedicinaService.cs
  Codigo/CuidadoWeb/Core/Service/IExameService.cs
  Codigo/CuidadoWeb/Core/Service/IFonteRendaService.cs
  Codigo/CuidadoWeb/Core/Service/IFornecedorOrganizacaoService.cs
  Codigo/CuidadoWeb/Core/Service/IFornecedorService.cs
  Codigo/CuidadoWeb/Core/Service/IFuncionarioService.cs
  Codigo/CuidadoWeb/Core/Service/IOrganizacaoService.cs
  Codigo/CuidadoWeb/Core/Service/IPlanejamentoCuidadoDiarioService.cs
  Codigo/CuidadoWeb/Core/Service/IPlanejamentoCuidadoService.cs
  Codigo/CuidadoWeb/Core/Service/IPlanoAssistenciaService.cs
  Codigo/CuidadoWeb/Core/Service/IPlanoSaudeService.cs
  Codigo/CuidadoWeb/Core/Service/IProdutoService.cs
  Codigo/CuidadoWeb/Core/Service/IResidenteService.cs
  Codigo/CuidadoWeb/Core/Service/IResponsavelService.cs
  Codigo/CuidadoWeb/Core/Service/ITipoCuidadoService.cs
  Codigo/CuidadoWeb/Core/Service/ITipoExameService.cs
  Codigo/CuidadoWeb/Core/Service/IVisitaService.cs
  Codigo/CuidadoWeb/Core/Service/IVisitanteService.cs
  Codigo/CuidadoWeb/CuidadoWeb/Program.cs
  Codigo/CuidadoWeb/Service/CuidadoService.cs
Labels: enhancement

#98 Adicionando Service do Manter Visita #94
  Codigo/CuidadoWeb/Core/Service/IVisitaService.cs
  Codigo/CuidadoWeb/Service/VisitaService.cs
Labels: enhancement

#104 Adição de componentes básicos do design system.
  Codigo/CuidadoWeb/CuidadoWeb/Views/Home/Index.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Shared/_Layout.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/DMSans/DMSans-Italic.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/DMSans/DMSans.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/DMSans/OFL.txt
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/DMSans/README.txt
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/DMSans/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/bold/Phosphor-Bold.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/bold/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/duotone/Phosphor-Duotone.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/duotone/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/fill/Phosphor-Fill.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/fill/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/light/Phosphor-Light.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/light/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/regular/Phosphor.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/regular/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/thin/Phosphor-Thin.ttf
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/fonts/phosphor/thin/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/logo/colorful.svg
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/assets/logo/colorless.svg
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/bar/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/site.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/js/script.js
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/js/site.js
Labels: enhancement

#109 Revert "Adicionando Controller do Manter Visita #97"
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/VisitaController.cs
Labels: fix

#108 Revert "Adicionando Mapper do Manter Visita #96"
  Codigo/CuidadoWeb/CuidadoWeb/Mappers/VisitaProfile.cs
Labels: fix

#107 Revert "Adicionando View Model do Manter Visita #95"
  Codigo/CuidadoWeb/CuidadoWeb/Models/VisitaViewModel.cs
  Codigo/CuidadoWeb/CuidadoWeb/Models/VisitanteViewModel.cs
Labels: fix

#106 Revert "Adicionando Service do Manter Visita #94"
  Codigo/CuidadoWeb/Core/Service/IVisitaService.cs
  Codigo/CuidadoWeb/Service/VisitaService.cs
Labels: fix
