Repository marcosdosea/Cuidado, pull requests merged in 2024-10, with the labels that each got.

#115 Design da home page.
  Codigo/CuidadoWeb/CuidadoWeb/Views/Shared/_Layout.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Shared/_Layout.cshtml.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/bar/side.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/bar/style.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/bar/top.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/style.css
  Codigo/CuidadoWeb/Service/CuidadoService.cs
Labels: enhancement

#122 Continuos Integration (CI)
  .github/workflows/dotnet.yml
Labels: enhancement

#123 Criação das views Do visitante
  Codigo/CuidadoWeb/Core/CuidadoContext.cs
  Codigo/CuidadoWeb/CuidadoWeb/CuidadoWeb.csproj
  Codigo/CuidadoWeb/CuidadoWeb/Views/Visitante/Create.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Visitante/Delete.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Visitante/Details.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Visitante/Edit.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Visitante/Index.cshtml
  Gerenciamento/DocumentodepadraocodificacaoBD.sql
Labels: enhancement

#103 Views Adicionadas do Manter Produto.
  Codigo/CuidadoWeb/Core/DTO/FuncionarioDTO.cs
  Codigo/CuidadoWeb/Core/Service/IFuncionarioService.cs
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/FuncionarioController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Mappers/FuncionarioProfile.cs
  Codigo/CuidadoWeb/CuidadoWeb/Views/Funcionario/BuscarFuncionarioPorCpf.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Funcionario/Index.cshtml
  Codigo/CuidadoWeb/Service/FuncionarioService.cs
Labels: enhancement

#120 Adição da controladora manager.
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/HomeController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/ManagerController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/ResidenteController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Views/Home/Privacy.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Manager/Index.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Shared/_Layout.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/bar/side.css
Labels: enhancement

#119 Correções para algumas issues, ver descrição.
  Codigo/CuidadoWeb/CuidadoWeb/Views/Shared/_Layout.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/bar/side.css
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/bar/top.css
Labels: enhancement, fix

#125 design view create visitante
  Codigo/CuidadoWeb/CuidadoWeb/Views/Visitante/Create.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/style.css
Labels: enhancement

#138 Criação dos testes
  Codigo/CuidadoWeb/Core/CuidadoContext.cs
  Codigo/CuidadoWeb/Core/Service/IVisitanteService.cs
  Codigo/CuidadoWeb/CuidadoWeb.sln
  Codigo/CuidadoWeb/CuidadoWeb/Views/Funcionario/Index.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Visitante/Create.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/style.css
  Codigo/CuidadoWeb/ServiceTests/ServiceTests.csproj
  Codigo/CuidadoWeb/ServiceTests/VisitanteServiceTests.cs
Labels: enhancement, teste

#143 Adicionado cards a tela de gerenciamento.
  Codigo/CuidadoWeb/CuidadoWeb/Models/CardViewModel.cs
  Codigo/CuidadoWeb/CuidadoWeb/Views/Manager/Index.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Manager/_Card.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/Views/Shared/_Layout.cshtml
  Codigo/CuidadoWeb/CuidadoWeb/wwwroot/css/style.css
Labels: enhancement

#145 implementado testes para service cuidado
  Codigo/CuidadoWeb/ServiceTests/CuidadoServiceTests.cs
Labels: enhancement, teste

#147 adicionado cards de operações
  Codigo/CuidadoWeb/CuidadoWeb/Controllers/ManagerController.cs
  Codigo/CuidadoWeb/CuidadoWeb/Views/Manager/Operations.cshtml
Labels: enhancement
